### ISSUE TITLE
Use staging page for map app trials - map app fails to display layers correctly

### ISSUE THREAD

**Issue by nilsnolde** [svalbox/arcgis-scripts#4]
For https://svalbox.no/map the layer `Svalbard - Virtual Outcrops (2)` can't be added to the map. 

I'd suggest to create a "test" page in WP where you can play around with ArcGIS Online web apps before publishing anything to the live frontend.

**Comment by PeterBetlem** [comment]
`Svalbard - Virtual Outcrops (2)` layer is actually the new layer that is connected to the testing database also used for the WordPress posts. But interestingly enough, I actually QC'd the frontend both from within and outside the UNIS domain, and it all worked fine when published. Probably comes down to republishing the service in Arcmap. I'll see what I can do from here.

**Comment by nilsnolde** [comment]
Yeah I don't doubt it man. Arc is a little punk, does whatever the f*** it wants.

**Comment by PeterBetlem** [comment]
Service published with port number - which ArcGIS really didn't seem to like. It should be functional now, even outside the UNIS domain.

**Comment by nilsnolde** [comment]
Yep, works. Still worth a thought if you wanna keep scratch layers live on svalbox.

**Comment by PeterBetlem** [comment]
Yea, I'll merge it with the existing layer as soon as I have time.
